<a href="https://colab.research.google.com/github/Adigozalovh/DeepLearning/blob/main/Introduciton_to_DeepLearning_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
A = torch.tensor([
    [1.0, 4.0, 7.0],
    [2.0, 3.0, 6.0]
])

In [3]:
A

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [4]:
X = torch.tensor([
    [1.0, 4.0, 7.0],
     [2.0, 3.0, 6.0]
], dtype = torch.bfloat16)

In [5]:
X

tensor([[1., 4., 7.],
        [2., 3., 6.]], dtype=torch.bfloat16)

In [6]:
X.shape

torch.Size([2, 3])

In [7]:
X.dtype

torch.bfloat16

In [8]:
X[0,1]

tensor(4., dtype=torch.bfloat16)

In [9]:
X[:,1]

tensor([4., 3.], dtype=torch.bfloat16)

In [10]:
X.abs()

tensor([[1., 4., 7.],
        [2., 3., 6.]], dtype=torch.bfloat16)

In [11]:
torch.abs(X)

tensor([[1., 4., 7.],
        [2., 3., 6.]], dtype=torch.bfloat16)

### torch.cos(), torch.exp(), torch.max(), torch.mean(), torch.sqrt()

In [14]:
X.sqrt()

tensor([[1.0000, 2.0000, 2.6406],
        [1.4141, 1.7344, 2.4531]], dtype=torch.bfloat16)

In [15]:
10 * (X + 1.0)

tensor([[20., 50., 80.],
        [30., 40., 70.]], dtype=torch.bfloat16)

In [16]:
X.exp()

tensor([[   2.7188,   54.5000, 1096.0000],
        [   7.3750,   20.1250,  404.0000]], dtype=torch.bfloat16)

In [18]:
X.mean()

tensor(3.8281, dtype=torch.bfloat16)

In [25]:
X.max(dim= 0) #keepdim = True

torch.return_types.max(
values=tensor([2., 4., 7.], dtype=torch.bfloat16),
indices=tensor([1, 0, 0]))

 dim = 0 burdaki dim axisdir dim = 0 olanda her sutun uzre max qiymetleri verir, dim = 1 olanda ise setir uzre baxir ve max qiymetlerini verir


In [26]:
X

tensor([[1., 4., 7.],
        [2., 3., 6.]], dtype=torch.bfloat16)

In [27]:
X @ X.T

tensor([[66., 56.],
        [56., 49.]], dtype=torch.bfloat16)

In [28]:
import numpy as np



In [30]:
A.numpy()

array([[1., 4., 7.],
       [2., 3., 6.]], dtype=float32)

In [31]:
torch.tensor(np.array([[1., 4., 7.],
                      [2., 3., 6.]]))

tensor([[1., 4., 7.],
        [2., 3., 6.]], dtype=torch.float64)

deeplearningsw 32-bit istifadə etmək daha uyğundur çünki RAM istifadəsini yarıya endirir və hesablamaları sürətləndirir. Elave olaraq neyron şəbəkələr 64-bit üzən vergüllü ədədlərin verdiyi əlavə dəqiqliyə əslində ehtiyac duymur.

In [33]:
N = torch.FloatTensor(np.array([ [1., 4., 7.],
                             [2., 3., 6]]))

#bu o ise yariyir ki avtomatik olaraq arrayi 32 bite cevirir

In [36]:
N.dtype

torch.float32

In [38]:
N

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [39]:
X[:, 1] = -99
X

tensor([[  1., -99.,   7.],
        [  2., -99.,   6.]], dtype=torch.bfloat16)

In [40]:
X.relu()

tensor([[1., 0., 7.],
        [2., 0., 6.]], dtype=torch.bfloat16)

X.relu() nun mentiqi odu ki, X arrayinda olan menfi deyerleri 0 edir musbetleri ise oldugu kimi saxlayir. Adeten hidden layerlarda olur

In [41]:
X

tensor([[  1., -99.,   7.],
        [  2., -99.,   6.]], dtype=torch.bfloat16)

In [43]:
if torch.cuda.is_available():
  device = "cuda"
elif torch.backends.mps.is_available():
  device = "mps"
else:
  device = "cpu"

Bu kod PyTorch-da modelin hansı hardware üzərində işləyəcəyini avtomatik seçmək üçündür: GPU (CUDA / Apple MPS) və ya CPU. Deeplearning ucun ideal hesab olunan cuda dir cunki en suretlisi odu

In [44]:
device

'cuda'

In [45]:
!nvidia-smi

Thu Jan 29 21:49:42 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P8              9W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

Bu kod NVIDIA GPU nun veziyyetini yoxlamag ucundu

In [46]:

M = torch.tensor([
    [1., 2., 3.],
    [4., 5., 6.]
])

M = M.to(device)


M ilk once buarada cpuda yaradilib amma sondaki M.to(device) kodu vasitesile onceden secilmis hardware uzerine kocurur(cuda, mps, cpu, ve s.)

In [47]:
M

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

In [48]:
M.device

device(type='cuda', index=0)

In [49]:
M = torch.tensor([[1.,2.,3.], [4.,5.,6.]], device = device)

In [50]:
R = M @ M.T

In [51]:
R

tensor([[14., 32.],
        [32., 77.]], device='cuda:0')

In [53]:
M = torch.rand((1000,1000)) #on the CPU
%timeit M @ M.T

M = torch.rand((1000,1000), device = "cuda") # on the GPu
%timeit M @ M.T

18.4 ms ± 3.02 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
608 µs ± 15.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


CPU ile GPU arasindaki vaxt serfiyyati muqayisesi. Matrisin olcusu ne qeder boyuyerse GPU CPU ya nisbetde aralarindaki vaxt daha da boyuyer amma cox kicik olculu matrislerde ise tam tersine CPU daha tez bitirmis olar emeliyyati GPU ya nisbetde

In [58]:
x = torch.tensor(5.0, requires_grad=True)
f = x ** 2
f

tensor(25., grad_fn=<PowBackward0>)

requires_grad=True → PyTorch-a deyirsən ki:
“Bu dəyişənə görə törəmə (gradient) hesablanacaq”

In [59]:
f.backward()
x.grad

tensor(10.)

In [60]:
learning_rate = 0.1
with torch.no_grad():
  x -= learning_rate * x.grad  #gradient descent step

learning_rate = 0.1
Bu öyrənmə sürətidir
Modelin necə böyük addımlarla irəlilədiyini müəyyən edir


In [61]:
x


tensor(4., requires_grad=True)

In [63]:
x_detached = x.detach()
x_detached -= learning_rate * x.grad

x_detached x in deyerlerinin kopyasidir. gradient izlemeden deyerleri goturur.

Əgər requires_grad=True olan tensoru birbaşa dəyişsən, PyTorch problem yarada bilər.
detach() manual hesablamalar ve debug üçündur

x_detached -= learning_rate * x.grad
Burda Gradient hesablanmır ve hec bir grad_fn yoxdur

detach() → “bu tensoru gradient sistemindən ayır, amma dəyərini saxla.”

In [64]:
x_detached

tensor(3.)

In [67]:
x.grad.zero_()

tensor(0.)

Bu kod x-in gradientini 0-a sıfırlayır. PyTorch-da gradientlər üst-üstə yığılır. Yeni backward() çağırmazdan əvvəl sıfırlamazsan, köhnə gradient-lər də əlavə olunacaq.

In [69]:
learning_rate = 0.1
x = torch.tensor(5.0, requires_grad = True)
for iteration in range(100):
  f = x ** 2  # forward pass
  f.backward()   #backward pass
  with torch.no_grad():
    x -= learning_rate * x.grad  #gradient descent step
  print(x)
  x.grad.zero_()   #reset the gradients

tensor(4., requires_grad=True)
tensor(3.2000, requires_grad=True)
tensor(2.5600, requires_grad=True)
tensor(2.0480, requires_grad=True)
tensor(1.6384, requires_grad=True)
tensor(1.3107, requires_grad=True)
tensor(1.0486, requires_grad=True)
tensor(0.8389, requires_grad=True)
tensor(0.6711, requires_grad=True)
tensor(0.5369, requires_grad=True)
tensor(0.4295, requires_grad=True)
tensor(0.3436, requires_grad=True)
tensor(0.2749, requires_grad=True)
tensor(0.2199, requires_grad=True)
tensor(0.1759, requires_grad=True)
tensor(0.1407, requires_grad=True)
tensor(0.1126, requires_grad=True)
tensor(0.0901, requires_grad=True)
tensor(0.0721, requires_grad=True)
tensor(0.0576, requires_grad=True)
tensor(0.0461, requires_grad=True)
tensor(0.0369, requires_grad=True)
tensor(0.0295, requires_grad=True)
tensor(0.0236, requires_grad=True)
tensor(0.0189, requires_grad=True)
tensor(0.0151, requires_grad=True)
tensor(0.0121, requires_grad=True)
tensor(0.0097, requires_grad=True)
tensor(0.0077, requires_